name: wheels

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest
            name: macos-x86_64
            macos_arch: "x86_64"
          # - os: macos-latest
          #   name: macos-arm64
          #   macos_arch: "arm64"

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.2
        env:
          CIBW_TEST_COMMAND: python -c "import solpos; print(solpos.solpos(2022, 10, 16, 15, 27, 13, 2, 52, 7))"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_ARCHS_WINDOWS : "AMD64 x86 ARM64"
          CIBW_ARCHS_MACOS: "${{ matrix.macos_arch }}"
          CIBW_SKIP: "pp*"
          CIBW_BUILD: "cp37*"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
